@host = http://127.0.0.1:6000/v1/users

GET {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Imxob3JhIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTU4OTQ0fQ.CB1as3-QfZxj8uAVaYbb5Ar2gMELAqTlzTSWzBfNoMc HTTP/1.1


###
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id" : 1,
    "username" : "johnny",
    "password" : "papa"
}


###
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id" : 3,
    "username" : "elton",
    "password" : "john"
}


### 
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[5]

###
GET {{host}}/?fields=username HTTP/1.1